Fix 429 errors
sivel/speedtest-cli pull request #796
Opened 2023-02-10 10:53 UTC by Notmarrco

This PR uses the one from @marksmayo

2023-02-20 14:36 UTC, sylvaindd commented
Just tried it and works fine for me.
My HomeAssistant integration hasn't been working for quite a few months now because of this issue.

It would be really nice if this could be merged and released

2023-03-02 18:57 UTC, mabed-fr commented
Same 429 cli and http ..

```
~ → curl -iL https://www.speedtest.net/speedtest-servers.php
HTTP/2 429 
date: Thu, 02 Mar 2023 18:57:11 GMT
content-type: text/html
content-length: 591
retry-after: 0
accept-ranges: bytes
cf-cache-status: DYNAMIC
set-cookie: __cf_bm=lsVV04VP4EnXe_XACbglTNypxfwSwVdCSBZCsKmb5_A-1677783431-0-AfzPaNeYOsnL5DGl66fR1OEsrx7cZqQIPsosKJdrzyfOmli02FaYmmpSXco13lETXCmgU0VgfrY5Mk2mj/t5r+U=; path=/; expires=Thu, 02-Mar-23 19:27:11 GMT; domain=.www.speedtest.net; HttpOnly; Secure; SameSite=None
server: cloudflare
cf-ray: 7a1bdd2f09e40d73-MRS

<html><head><title>Too Many Requests</title></head><body><h1>429 Error - Too Many Requests</h1><p>Your IP address is making too many requests. We ask that you limit requests to no more than 1 per second.</p><p>We make an attempt to be flexible, allowing small bursts in traffic. You have exceeded this threshold however and have been blocked.</p><p>Please reduce the speed at which your requests are made and try again after a while. If you feel you have reached this message in error, please contact us at noc @ speedtest.net and reference this error code.</p><p>Thank you</p></body></html>
```

![speedtest_broken](https://user-images.githubusercontent.com/25350431/222525171-6c7f2c16-d3cc-41d6-8a63-d5db7cd2bdac.png)

2023-03-03 16:13 UTC, marcthegreate commented
Ok, I apologize, I was not aware I am very new at Github and also CLI stuff, so could I just use the CLI command networkquality instead?

Brian Lauterbach - Sent using Spark Mail from Apple© MacBook Air M2
Sent with Spark
On Mar 2, 2023 at 12:58 PM -0600, Mathieu BEDOS ***@***.***>, wrote:
> Same 429 cli and http ..
> ~ → curl -iL https://www.speedtest.net/speedtest-servers.php
>
> HTTP/2 429
>
> date: Thu, 02 Mar 2023 18:57:11 GMT
>
> content-type: text/html
>
> content-length: 591
>
> retry-after: 0
>
> accept-ranges: bytes
>
> cf-cache-status: DYNAMIC
>
> set-cookie: __cf_bm=lsVV04VP4EnXe_XACbglTNypxfwSwVdCSBZCsKmb5_A-1677783431-0-AfzPaNeYOsnL5DGl66fR1OEsrx7cZqQIPsosKJdrzyfOmli02FaYmmpSXco13lETXCmgU0VgfrY5Mk2mj/t5r+U=; path=/; expires=Thu, 02-Mar-23 19:27:11 GMT; domain=.www.speedtest.net; HttpOnly; Secure; SameSite=None
>
> server: cloudflare
>
> cf-ray: 7a1bdd2f09e40d73-MRS
>
>
>
> <html><head><title>Too Many Requests</title></head><body><h1>429 Error - Too Many Requests</h1><p>Your IP address is making too many requests. We ask that you limit requests to no more than 1 per second.</p><p>We make an attempt to be flexible, allowing small bursts in traffic. You have exceeded this threshold however and have been blocked.</p><p>Please reduce the speed at which your requests are made and try again after a while. If you feel you have reached this message in error, please contact us at noc @ speedtest.net and reference this error code.</p><p>Thank you</p></body></html>
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-03-03 16:21 UTC, mabed-fr commented
> Ok, I apologize, I was not aware I am very new at Github and also CLI stuff, so could I just use the CLI command networkquality instead? Brian Lauterbach - Sent using Spark Mail from Apple© MacBook Air M2 Sent with Spark
> […](#)
> On Mar 2, 2023 at 12:58 PM -0600, Mathieu BEDOS ***@***.***>, wrote: Same 429 cli and http .. ~ → curl -iL https://www.speedtest.net/speedtest-servers.php HTTP/2 429 date: Thu, 02 Mar 2023 18:57:11 GMT content-type: text/html content-length: 591 retry-after: 0 accept-ranges: bytes cf-cache-status: DYNAMIC set-cookie: __cf_bm=lsVV04VP4EnXe_XACbglTNypxfwSwVdCSBZCsKmb5_A-1677783431-0-AfzPaNeYOsnL5DGl66fR1OEsrx7cZqQIPsosKJdrzyfOmli02FaYmmpSXco13lETXCmgU0VgfrY5Mk2mj/t5r+U=; path=/; expires=Thu, 02-Mar-23 19:27:11 GMT; domain=.[www.speedtest.net](http://www.speedtest.net); HttpOnly; Secure; SameSite=None server: cloudflare cf-ray: 7a1bdd2f09e40d73-MRS <html><head><title>Too Many Requests</title></head><body><h1>429 Error - Too Many Requests</h1><p>Your IP address is making too many requests. We ask that you limit requests to no more than 1 per second.</p><p>We make an attempt to be flexible, allowing small bursts in traffic. You have exceeded this threshold however and have been blocked.</p><p>Please reduce the speed at which your requests are made and try again after a while. If you feel you have reached this message in error, please contact us at noc @ speedtest.net and reference this error code.</p><p>Thank you</p></body></html> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Good morning,

That's not the topic but yes

2023-09-16 21:26 UTC, dirrgang commented
This is the automation I now set up to call the update randomly between 1:00 and 5:00 AM.

```
alias: Speedtest
description: ""
trigger:
  - platform: time
    at: "01:00:00"
condition: []
action:
  - delay: "{{ (range(1, 5)|random|int) }}:{{ (range(1, 60)|random|int) }}:00"
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
        - sensor.speedtest_ping
mode: single

```

2024-05-04 19:51 UTC, jpph commented
Can it be updated ?
Freebsd package is failing to retrive server list

2024-05-09 11:21 UTC, TheTumultuousUnicornOfDarkness commented
I tested your script by using `curl -s https://raw.githubusercontent.com/Notmarrco/speedtest-cli/master/speedtest.py | python3 -`: it works like a charm, thanks.
Hope this PR will be merged soon.

2024-06-27 22:58 UTC, imclint21 commented
Seems like this problem happen often in France

2024-08-15 09:19 UTC, NeckBeardPrince commented
> I tested your script by using `curl -s https://raw.githubusercontent.com/Notmarrco/speedtest-cli/master/speedtest.py | python3 -`: it works like a charm, thanks. Hope this PR will be merged soon.

Testing this I get

```console
Retrieving speedtest.net configuration...
Cannot retrieve speedtest configuration
ERROR: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
```

2024-10-28 18:22 UTC, JonasZaoui2 commented
I got the same error since few days ..

2025-04-03 15:26 UTC, toby-bro requested changes
Hello,
It's impossible to review the PR as you changed all the quotation marks, can this change be reverted please ? (I know the repo is dead but I have this error too and wanted to see what you did to understand your changes and it is a pain to find what is interesing). 
Thank you for the PR anyway.

2025-08-18 18:55 UTC, bberstel commented
I tried to extract the relevant changes from the PR. The diff is attached below (with one debug addition from me).

[speedtest.py.patch](https://github.com/user-attachments/files/21842069/speedtest.py.patch)

2025-08-18 21:29 UTC, toby-bro commented
> I tried to extract the relevant changes from the PR. The diff is attached below (with one debug addition from me).
> [speedtest.py.patch](https://github.com/user-attachments/files/21842069/speedtest.py.patch)

Thanks a lot,
Could you open a separate PR with the patch ? (it would be easier to review the change)

2025-08-19 13:00 UTC, bberstel commented
> Thanks a lot, Could you open a separate PR with the patch ? (it would be easier to review the change)

Here it is: https://github.com/sivel/speedtest-cli/pull/813

2026-01-08 13:49 UTC, laurent-luyckx-keemotion commented
Hi. Changes from @bberstel are working fine. Can this be merged please? 
Thank you very much.

2026-04-30 15:53 UTC, closed without merging